# Proyek Akhir: Menyelesaikan Permasalahan Perusahaan Edutech - Jaya Jaya Institut

- Nama: Nurya Fahru Rosyidin
- Email: nurya.fahrurosyidin@gmail.com
- Id Dicoding: nuryafahrurosyidin

## Persiapan

### Menyiapkan library yang dibutuhkan

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine
from getpass import getpass

### Menyiapkan data yang akan digunakan

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Load dataset dari repository Github
# url = "https://raw.githubusercontent.com/NuryaFahruRosyidin2406/Submission-Akhir-Dicoding-Menyelesaikan-Permasalahan-Institusi-Pendidikan/refs/heads/main/Dataset/students_performance/data.csv?token=GHSAT0AAAAAAEIQKDBDDAYP2WGJBY46QJ5M2VOCH2A"
url = "/content/drive/MyDrive/Colab_Notebooks/Dataset/Submission_Akhir_Dicoding_Performa_Siswa/students_performance/data.csv"
# df = pd.read_csv(url, encoding='windows-1252')
df = pd.read_csv(url)
df.head()

  Marital_status;Application_mode;Application_order;Course;Daytime_evening_attendance;Previous_qualification;Previous_qualification_grade;Nacionality;Mothers_qualification;Fathers_qualification;Mothers_occupation;Fathers_occupation;Admission_grade;Displaced;Educational_special_needs;Debtor;Tuition_fees_up_to_date;Gender;Scholarship_holder;Age_at_enrollment;International;Curricular_units_1st_sem_credited;Curricular_units_1st_sem_enrolled;Curricular_units_1st_sem_evaluations;Curricular_units_1st_sem_approved;Curricular_units_1st_sem_grade;Curricular_units_1st_sem_without_evaluations;Curricular_units_2nd_sem_credited;Curricular_units_2nd_sem_enrolled;Curricular_units_2nd_sem_evaluations;Curricular_units_2nd_sem_approved;Curricular_units_2nd_sem_grade;Curricular_units_2nd_sem_without_evaluations;Unemployment_rate;Inflation_rate;GDP;Status
0  1;17;5;171;1;1;122.0;1;19;12;5;9;127.3;1;0;0;1...
1  1;15;1;9254;1;1;160.0;1;1;3;3;3;142.5;1;0;0;0;...
2  1;1;5;9070;1;1;122.0;1;37;37;9;9;124.8;1;0;0;0...
3  1;17;2;9773;1;1;122.0;1;38;37;5;3;119.6;1;0;0;...
4  2;39;1;8014;0;1;100.0;1;37;38;9;9;141.5;0;0;0;...

In [4]:
df = pd.read_csv(url, sep=';')
df.head()

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Previous_qualification_grade,Nacionality,Mothers_qualification,Fathers_qualification,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Status
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [5]:
# Menambahkan Header Index di awal
df.insert(0, 'index', range(1, len(df) + 1))

In [6]:
# Untuk menampilkan nama header
print(df.columns.tolist())

['index', 'Marital_status', 'Application_mode', 'Application_order', 'Course', 'Daytime_evening_attendance', 'Previous_qualification', 'Previous_qualification_grade', 'Nacionality', 'Mothers_qualification', 'Fathers_qualification', 'Mothers_occupation', 'Fathers_occupation', 'Admission_grade', 'Displaced', 'Educational_special_needs', 'Debtor', 'Tuition_fees_up_to_date', 'Gender', 'Scholarship_holder', 'Age_at_enrollment', 'International', 'Curricular_units_1st_sem_credited', 'Curricular_units_1st_sem_enrolled', 'Curricular_units_1st_sem_evaluations', 'Curricular_units_1st_sem_approved', 'Curricular_units_1st_sem_grade', 'Curricular_units_1st_sem_without_evaluations', 'Curricular_units_2nd_sem_credited', 'Curricular_units_2nd_sem_enrolled', 'Curricular_units_2nd_sem_evaluations', 'Curricular_units_2nd_sem_approved', 'Curricular_units_2nd_sem_grade', 'Curricular_units_2nd_sem_without_evaluations', 'Unemployment_rate', 'Inflation_rate', 'GDP', 'Status']

In [7]:
df.head()

,index,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Previous_qualification_grade,Nacionality,Mothers_qualification,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Status
0,1,1,17,5,171,1,1,122.0,1,19,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,2,1,15,1,9254,1,1,160.0,1,1,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,3,1,1,5,9070,1,1,122.0,1,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,4,1,17,2,9773,1,1,122.0,1,38,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,5,2,39,1,8014,0,1,100.0,1,37,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

## Data Understanding

In [8]:
# Informasi dari dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 38 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   index                                         4424 non-null   int64
 1   Marital_status                                4424 non-null   int64
 2   Application_mode                              4424 non-null   int64
 3   Application_order                             4424 non-null   int64
 4   Course                                        4424 non-null   int64
 5   Daytime_evening_attendance                    4424 non-null   int64
 6   Previous_qualification                        4424 non-null   int64
 7   Previous_qualification_grade                  4424 non-null   float64
 8   Nacionality                                   4424 non-null   int64
 9   Mothers_qualification                         4424 non-null   int64
 10  Fathers_qualification                         4424 non-null   int64
 11  Mothers_occupation                            4424 non-null   int64
 12  Fathers_occupation                            4424 non-null   int64
 13  Admission_grade                               4424 non-null   float64
 14  Displaced                                     4424 non-null   int64
 15  Educational_special_needs                     4424 non-null   int64
 16  Debtor                                        4424 non-null   int64
 17  Tuition_fees_up_to_date                       4424 non-null   int64
 18  Gender                                        4424 non-null   int64
 19  Scholarship_holder                            4424 non-null   int64
 20  Age_at_enrollment                             4424 non-null   int64
 21  International                                 4424 non-null   int64
 22  Curricular_units_1st_sem_credited             4424 non-null   int64
 23  Curricular_units_1st_sem_enrolled             4424 non-null   int64
 24  Curricular_units_1st_sem_evaluations          4424 non-null   int64
 25  Curricular_units_1st_sem_approved             4424 non-null   int64
 26  Curricular_units_1st_sem_grade                4424 non-null   float64
 27  Curricular_units_1st_sem_without_evaluations  4424 non-null   int64
 28  Curricular_units_2nd_sem_credited             4424 non-null   int64
 29  Curricular_units_2nd_sem_enrolled             4424 non-null   int64
 30  Curricular_units_2nd_sem_evaluations          4424 non-null   int64
 31  Curricular_units_2nd_sem_approved             4424 non-null   int64
 32  Curricular_units_2nd_sem_grade                4424 non-null   float64
 33  Curricular_units_2nd_sem_without_evaluations  4424 non-null   int64
 34  Unemployment_rate                             4424 non-null   float64
 35  Inflation_rate                                4424 non-null   float64
 36  GDP                                           4424 non-null   float64
 37  Status                                        4424 non-null   object
dtypes: float64(7), int64(30), object(1)
memory usage: 1.3+ MB

### Pengecekan dan pembersihan pada dataset

#### Pengecekan dan pembersihan Missing Values

In [9]:
missing_values = df.isnull().sum()
print(f"Jumlah kolom yang memiliki missing value: {missing_values[missing_values > 0].count()}")
if missing_values.sum() == 0:
  print("Hasil : Tidak ada missing value")
else:
  print(f"Hasil : Jumlah missing value: {missing_values.sum()}")

Jumlah kolom yang memiliki missing value: 0
Hasil : Tidak ada missing value

#### Pengecekan Data Duplikat

In [10]:
feature_cols = [col for col in df.columns if col != 'index']
duplicate_count = df.duplicated(subset=feature_cols).sum()
print(f"Jumlah data duplikat: {duplicate_count}")
if duplicate_count == 0:
  print("Hasil : Tidak ditemukan data duplikat")
else:
  print(f"Hasil : Jumlah data duplikat: {duplicate_count}")

Jumlah data duplikat: 0
Hasil : Tidak ditemukan data duplikat

#### Pengecekan Distribusi Nilai Unik pada Target

In [11]:
print(df['Status'].value_counts())

Status
Graduate    2209
Dropout     1421
Enrolled     794
Name: count, dtype: int64

#### Ringkasan Statistik untuk Memeriksa Anomali nilai

In [12]:
display(df.describe().T[['min', 'mean', 'max']])

                                                min         mean          max
index                                          1.00  2212.500000  4424.000000
Marital_status                                 1.00     1.178571     6.000000
Application_mode                               1.00    18.669078    57.000000
Application_order                              0.00     1.727848     9.000000
Course                                        33.00  8856.642631  9991.000000
Daytime_evening_attendance                     0.00     0.890823     1.000000
Previous_qualification                         1.00     4.577758    43.000000
Previous_qualification_grade                  95.00   132.613314   190.000000
Nacionality                                    1.00     1.873192   109.000000
Mothers_qualification                          1.00    19.561935    44.000000
Fathers_qualification                          1.00    22.275316    44.000000
Mothers_occupation                             0.00    10.960895   194.000000
Fathers_occupation                             0.00    11.032324   195.000000
Admission_grade                               95.00   126.978119   190.000000
Displaced                                      0.00     0.548373     1.000000
Educational_special_needs                      0.00     0.011528     1.000000
Debtor                                         0.00     0.113698     1.000000
Tuition_fees_up_to_date                        0.00     0.880651     1.000000
Gender                                         0.00     0.351718     1.000000
Scholarship_holder                             0.00     0.248418     1.000000
Age_at_enrollment                             17.00    23.265145    70.000000
International                                  0.00     0.024864     1.000000
Curricular_units_1st_sem_credited              0.00     0.709991    20.000000
Curricular_units_1st_sem_enrolled              0.00     6.270570    26.000000
Curricular_units_1st_sem_evaluations           0.00     8.299051    45.000000
Curricular_units_1st_sem_approved              0.00     4.706600    26.000000
Curricular_units_1st_sem_grade                 0.00    10.640822    18.875000
Curricular_units_1st_sem_without_evaluations   0.00     0.137658    12.000000
Curricular_units_2nd_sem_credited              0.00     0.541817    19.000000
Curricular_units_2nd_sem_enrolled              0.00     6.232143    23.000000
Curricular_units_2nd_sem_evaluations           0.00     8.063291    33.000000
Curricular_units_2nd_sem_approved              0.00     4.435805    20.000000
Curricular_units_2nd_sem_grade                 0.00    10.230206    18.571429
Curricular_units_2nd_sem_without_evaluations   0.00     0.150316    12.000000
Unemployment_rate                              7.60    11.566139    16.200000
Inflation_rate                                -0.80     1.228029     3.700000
GDP                                           -4.06     0.001969     3.510000

## Data Preparation / Preprocessing

Berdasarkan tahap data understanding:
- Tidak ditemukan missing value pada seluruh fitur
- Tidak ditemukannya data duplikat
- Distribusi berada pada rentang batas yang wajar sesuai dokumentasi dataset.

Sehingga, dapat dilanjut ke tahap EDA.

## Exploratory Data Analysis (EDA)

## Unggah ke Supabase

## Modeling

## Evaluation